# Generated by Django 5.2.1 on 2026-05-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(help_text='Comma-separated author names', max_length=500)),
                ('abstract', models.TextField()),
                ('category', models.CharField(choices=[('robotics', 'Robotics'), ('ai', 'Artificial Intelligence'), ('nlp', 'NLP & Devanagari'), ('connectivity', 'Connectivity'), ('hpc', 'High Performance Computing'), ('other', 'Other')], max_length=50)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=300)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='research/pdfs/')),
                ('github_url', models.URLField(blank=True, help_text='Link to GitHub repository')),
                ('external_url', models.URLField(blank=True, help_text='External paper link (arXiv, etc.)')),
                ('published_date', models.DateField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Research Publication',
                'verbose_name_plural': 'Research Publications',
                'ordering': ['-published_date'],
            },
        ),
    ]
