# Generated by Django 5.2.1 on 2026-07-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "media_url",
                    models.CharField(
                        help_text="Path to static file (e.g., static/img/robots/robot_after_3d_print.jpeg) or full URL",
                        max_length=500,
                    ),
                ),
                (
                    "thumbnail_url",
                    models.CharField(
                        blank=True,
                        help_text="Optional path to static thumbnail. Defaults to media_url if empty.",
                        max_length=500,
                    ),
                ),
                (
                    "caption",
                    models.TextField(
                        blank=True,
                        help_text="Optional text caption to show on the story",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        default="image",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Story",
                "verbose_name_plural": "Stories",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
