# Generated by Django 5.2.1 on 2026-08-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_populate_stories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text="Year label, e.g. '1983' or '2004–05'", max_length=20)),
                ('exact_date', models.DateField(blank=True, help_text='Optional exact date for sorting', null=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Ascending; used before year when equal')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('image', models.CharField(blank=True, help_text='Path to static image (optional)', max_length=500)),
                ('image_caption', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'History Milestones',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=100)),
                ('role_type', models.CharField(choices=[('founder', 'Founder'), ('engineer', 'Engineer'), ('researcher', 'Researcher'), ('staff', 'Staff')], default='staff', max_length=20)),
                ('bio', models.TextField()),
                ('photo', models.CharField(help_text='Path to static profile image', max_length=500)),
                ('portfolio_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('scholar_url', models.URLField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='researchpublication',
            name='venue',
            field=models.CharField(blank=True, help_text="Journal, conference, or 'Preprint'", max_length=200),
        ),
        migrations.AlterField(
            model_name='researchpublication',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='researchpublication',
            name='external_url',
            field=models.URLField(blank=True, help_text='External paper link (arXiv, DOI, etc.)'),
        ),
    ]
