# Generated by Django 5.2.1 on 2026-08-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_mp4_stories_and_history_enrichment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(help_text="Stable key, e.g. 'video' or 'image_1'. Never changes after creation.", max_length=50, unique=True)),
                ('label', models.CharField(blank=True, help_text='Short label shown to viewers', max_length=120)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='product_media/')),
                ('fallback_path', models.CharField(blank=True, help_text='Optional static/media path used if no uploaded file is set, e.g. /static/img/robots/x.jpeg or /video/f.mp4', max_length=500)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Media Slot',
                'verbose_name_plural': 'Product Media Slots',
                'ordering': ['sort_order', 'slot'],
            },
        ),
    ]
