jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set working dir
        run: |
          echo "Working dir:"
          ls -la
          cd <your-subfolder-if-any>
          ls -la

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd <your-subfolder-if-any>
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Migrate
        run: |
          cd <your-subfolder-if-any>
          source venv/bin/activate
          python manage.py migrate

      - name: Collect static
        run: |
          cd HTP
          source venv/bin/activate
          python manage.py collectstatic --noinput
